main.native:
	ocamlbuild -use-ocamlfind -cflags '-cclib -I/usr/local/uppaal/include' -lflags '-cclib -lstdc++ -cclib -std=c++11 -cclib -L/usr/local/uppaal/lib -cclib -ludbm' main.native 
main.byte:
	ocamlbuild -use-ocamlfind -cflags '-cclib -I/usr/local/uppaal/include' -lflags '-cclib -lstdc++ -cclib -std=c++11 -cclib -L/usr/local/uppaal/lib -cclib -ludbm' main.byte


